#!/bin/sh
# Flopctl: A rudimentary "control center" app for Floppinux.
# Usage: flopctl get|set|config|launch target
do_get()
{
case "$1" in
 prompt) echo "PS1";break;;
 uname) cat /proc/version;break;;
 cpuinfo) cat /proc/$1;break;;
 env) set;break;;
 hostname) cat /etc/hostname;break;;
 *) echo "Cannot get property: $1";break;;
 esac
 }

do_set()
{
case "$1" in
 prompt) export PS1="$2";break;;
 *) echo "Cannot set property: $1";break;;
esac
}

do_config()
{
case "$1" in
 shutdown) vi /home/shutdown.sh;break;;
 profile) vi /etc/profile;break;;
 hostname) vi /etc/hostname;break;;
 *) echo "Cannot configure property: $1";break;;
esac
}

do_launch()
{
case "$1" in
 sh|shell) sh -l -m;break;;
 *) echo "Cannot launch $1";break;;
esac
}

main()
{
do_$1 $2 $3
}

main $*
